### ISSUE TITLE
Change combo dropdown width

### ISSUE THREAD

**Issue by tongtoanbs** [ndm2/ckeditor-placeholder-elements#10]
How can I change the width of this placeholder combo dropdown? because my label is very long.
I tried to search in google and found that I can change the width of combo box by using css class, but it's gonna change the other dropdown too, I just want only this placeholder dropdown to increase width. Is is possible?

**Comment by ndm2** [comment]
That's more of a general CKEditor/RichCombo Plugin question/problem.

Anyways, all rich combo panels do get a class added that consists of the constant `cke_combopanel__` combined with the lowercased name of the UI element, in this case `placeholderelements`, resulting in `cke_combopanel__placeholderelements`.

So you can simply create a rule for this class in your styles and apply your desired width, like

```css
.cke_combopanel__placeholderelements {
	width: 300px;
}
```

Please note that the name of the UI element will change in the future in order to match the naming scheme used in other places, ie `placeholder_elements`, so you may want to include `.cke_combopanel__placeholder_elements` too.
